# Generated by Django 5.2.17 on 2026-09-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'expense_date'], name='expense_owner_date_idx'), models.Index(fields=['owner', 'category', 'expense_date'], name='expense_owner_cat_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='expense_amount_minor_positive'), models.CheckConstraint(condition=models.Q(('amount_minor__lte', 9007199254740991)), name='expense_amount_minor_js_safe')],
            },
        ),
    ]
